project:
  type: website
  output-dir: docs
  # render: 
  #   - "!essay.qmd"


website:
  title: Valentina Salcedo
  favicon: "media/logo2.0.png"
  open-graph: true
  navbar:
    title: Valentina Salcedo
    description: Journalist and writer based in Trieste, Italy
    # logo: "media/logo2.1 rectangle.png"
    # logo-alt: "Logo with a stylized E, D and L"
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: essay.qmd
        text: Essay
      - href: articles.qmd
        text: Articles
  page-footer:
    background: light # or `dark`
    # left: |
      # DE LUCA ERIK, P.IVA: IT01401250327 <br>
      # Sede legale: Via dei Giardini, 50 - 34146 - Trieste
    center: |
      Copyright 2025, Valentina Salcedo
    right: |
      This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/){target=_blank} by [Erik De Luca](https://erikdeluca.it){target=_blank}.
  cookie-consent:
    type: express
    # style: headline
    palette: light
  google-analytics:
    tracking-id: G-6Q1YFXHZT8
    anonymize-ip: true
  site-url: https://valentinasalcedo.github.io
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme:
      - cosmo
      # - styles.scss
    # mainfont: figtree
    # titlefont: parkinsans
    light: minty
    dark: solar
    toc: true
    page-layout: full
    code-fold: true
    df-print: paged
    warnings: false
    include-in-header:
          - text: |
              <meta name="google-site-verification" content="googlebe81db27a25d8fa3googlebe81db27a25d8fa3" />
execute:
  freeze: auto